In [1]:
import torch
import numpy as np

Create 5x3 empty tensor

In [2]:
x = torch.empty(5, 3)
y = np.empty((5, 3))
print(x)
print(y)

tensor([[7.5767e-33, 4.5671e-41, 7.5767e-33],
        [4.5671e-41, 1.3458e-14, 6.3371e-10],
        [1.1128e+27, 1.3566e-14, 1.7442e+28],
        [4.9108e-14, 1.3556e-19, 2.2842e+20],
        [1.1048e-32, 1.3563e-19, 1.6114e-19]])
[[2.2265088e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


In [3]:
x = torch.rand(5, 3)
y = np.random.rand(5,3)
print(x)
print(y)

tensor([[0.0360, 0.0104, 0.4077],
        [0.6517, 0.0407, 0.3836],
        [0.2149, 0.5721, 0.5343],
        [0.3303, 0.5860, 0.3492],
        [0.6941, 0.5178, 0.2937]])
[[0.10810328 0.9571788  0.00910072]
 [0.08973242 0.21241102 0.75623632]
 [0.85365157 0.39651157 0.6059252 ]
 [0.38651925 0.3398051  0.74062275]
 [0.92155403 0.922392   0.04042154]]


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
y = np.zeros((5, 3), dtype=np.long)
print(x)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [5]:
x = torch.tensor([5.5, 3])
y = np.array([5.5, 3])
print(x)
print(y)

tensor([5.5000, 3.0000])
[5.5 3. ]


x.new_* will reuse the $datatype$ form $x$ and run in the same $device$ as defined in $x$

In [6]:
x = x.new_ones(5, 3) # with specify sizes but not override dtype
print(x)
print(x.dtype)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [7]:
x = torch.randn_like(x, dtype=torch.float) # override dtype,
                                            #but have the same sizes
print(x)
print(x.size())

tensor([[-1.5956, -1.0492, -0.2599],
        [ 0.9908,  1.0313, -1.0643],
        [-1.4485, -1.7315, -2.2369],
        [ 0.8530,  0.3488,  0.0254],
        [ 0.1322, -0.0687, -0.4062]])
torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)
print(torch.add(x, y))


res = torch.empty(5, 3)
torch.add(x, y, out=res)
print(res)

y.add_(x)
print(y)


tensor([[-1.2921, -0.6395,  0.2600],
        [ 1.1303,  1.8321, -1.0198],
        [-1.2395, -1.1146, -2.1232],
        [ 0.9927,  0.8913,  0.5203],
        [ 1.1002,  0.8574, -0.1759]])
tensor([[-1.2921, -0.6395,  0.2600],
        [ 1.1303,  1.8321, -1.0198],
        [-1.2395, -1.1146, -2.1232],
        [ 0.9927,  0.8913,  0.5203],
        [ 1.1002,  0.8574, -0.1759]])
tensor([[-1.2921, -0.6395,  0.2600],
        [ 1.1303,  1.8321, -1.0198],
        [-1.2395, -1.1146, -2.1232],
        [ 0.9927,  0.8913,  0.5203],
        [ 1.1002,  0.8574, -0.1759]])
tensor([[-1.2921, -0.6395,  0.2600],
        [ 1.1303,  1.8321, -1.0198],
        [-1.2395, -1.1146, -2.1232],
        [ 0.9927,  0.8913,  0.5203],
        [ 1.1002,  0.8574, -0.1759]])


In [9]:
print(x[:, 1]) # Slices

tensor([-1.0492,  1.0313, -1.7315,  0.3488, -0.0687])


Use torch.view to resize the tensor

In [10]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [11]:
x = np.random.rand(4, 4)
y = x.reshape(16)
z = x.reshape(-1, 8)
print(x.shape, y.shape, z.shape)

(4, 4) (16,) (2, 8)


## Converting a Torch Tensor to a NumPy array and vice versa


The Torch Tensor and Numpy array will share underlying memory locations (if the Torch Tensor is using CPU), and changing one will change the other

In [12]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [13]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [14]:
a.add_(1)
print(b)

[2. 2. 2. 2. 2.]


In [15]:
a = np.ones(5)
print(a)


[1. 1. 1. 1. 1.]


In [16]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [17]:
np.add(a, 1, out=a)
print(b)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## CUDA Tensor

In [18]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
x = torch.zeros(5, 3)
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## The different between torch.ones(), torch.ones_like() and torch.new_ones()

### Both torch.new_ones and torch.ones_like create a tensor from an existing tensor

new_ones(*size, dtype=None, device=None, requires_grad=False*) → Tensor
    
    Returns a Tensor of size *size* filled with 1. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

torch.ones_like(*input, dtype=None, layout=None, device=None, requires_grad=False*) → Tensor

    Returns a tensor filled with the scalar value 1, with the same *size* as input

### torch.ones creates new tensor from specify arguments

torch.ones(**size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False*) → Tensor
    
    Returns a tensor filled with the scalar value 1, with the shape defined by the variable argument *size*

torch.ones_like(input) is equivalent to torch.ones(input.size(), dtype=input.dtype, layout=input.layout, device=input.device)
